// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = never
type AppRouteHandlerRoutes = "/api/contact-leads" | "/api/newsletter-subscribers" | "/api/product-inquiries"
type PageRoutes = never
type LayoutRoutes = "/"
type RedirectRoutes = "/blog-detail-02/[[...path]]" | "/blog-grid" | "/blog-list" | "/catalogue" | "/catalouge" | "/coming-soon" | "/contact-02" | "/customer-feedback" | "/shop-collection" | "/shop-default-grid" | "/shop-default-grid/[[...path]]" | "/store-list-02/[[...path]]" | "/store-list/[[...path]]"
type RewriteRoutes = "/api/v1/[[...path]]"
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes | AppRouteHandlerRoutes


interface ParamMap {
  "/": {}
  "/api/contact-leads": {}
  "/api/newsletter-subscribers": {}
  "/api/product-inquiries": {}
  "/api/v1/[[...path]]": { "path"?: string[]; }
  "/blog-detail-02/[[...path]]": { "path"?: string[]; }
  "/blog-grid": {}
  "/blog-list": {}
  "/catalogue": {}
  "/catalouge": {}
  "/coming-soon": {}
  "/contact-02": {}
  "/customer-feedback": {}
  "/shop-collection": {}
  "/shop-default-grid": {}
  "/shop-default-grid/[[...path]]": { "path"?: string[]; }
  "/store-list-02/[[...path]]": { "path"?: string[]; }
  "/store-list/[[...path]]": { "path"?: string[]; }
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap, AppRouteHandlerRoutes }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }

  /**
   * Context for Next.js App Router route handlers
   * @example
   * ```tsx
   * export async function GET(request: NextRequest, context: RouteContext<'/api/users/[id]'>) {
   *   const { id } = await context.params
   *   return Response.json({ id })
   * }
   * ```
   */
  interface RouteContext<AppRouteHandlerRoute extends AppRouteHandlerRoutes> {
    params: Promise<ParamMap[AppRouteHandlerRoute]>
  }
}
